apiVersion: v1
kind: PersistentVolume

metadata:
  name: my-static-pv


spec:

  capacity:

    storage: 1Gi


  accessModes:

  - ReadWriteOnce


  persistentVolumeReclaimPolicy: Retain


  hostPath:

    path: /data/my-volume
